networks:
  proxy:
    external: true
services:

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - 9705:9705
    volumes:
      - /mnt/software/opt/downloads/huntarr:/config
    environment:
      - TZ=America/Chicago
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huntarr.rule=Host(`huntarr.hawknest.quest`)"
      - "traefik.http.routers.huntarr.entrypoints=websecure"
      - "traefik.http.routers.huntarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.huntarr.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.huntarr.loadbalancer.server.port=9705"
