####################################################
# HawkMox Configuration
####################################################

########################################
# Cluster
########################################

CLUSTER_NAME="HawkCluster"
CLUSTER_MASTER=""

########################################
# Storage
########################################

POOL_NAME="hawktank"
VM_DATASET="vmstore"
FILE_DATASET="hawkfiles"

ZFS_STORAGE_ID="hawktank"

DIR_STORAGE_ID="local"

########################################
# Network
########################################

DNS_SERVER="192.168.1.210"
TIME_SERVER=""

########################################
# System
########################################

ENABLE_TRIM=true
ENABLE_LOGROTATE=true
ENABLE_ZFS=true

########################################
# Hardware Limits
########################################

BOOT_DISK_MAX_GB=64
APP_DISK_MIN_GB=400
