#version: "3.9"

networks:
  proxy:
    external: true
  immich:
    driver: bridge

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    depends_on:
      - immich-redis
      - immich-db
    env_file:
      - .env
    volumes:
      - /mnt/.ix-apps/app_mounts/immich/config:/config
      - /mnt/HawkPool/Media/Center/photos:/usr/src/app/upload
    networks:
      - proxy
      - immich
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.hawknest.quest`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=3001"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.middlewares=secureHeaders@file"

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-ml
    restart: unless-stopped
    depends_on:
      - immich-redis
      - immich-db
    env_file:
      - .env
    volumes:
      - /mnt/.ix-apps/app_mounts/immich/config:/config
      - /mnt/HawkPool/Media/Center/photos:/usr/src/app/upload
    networks:
      - immich

  immich-redis:
    image: redis:7
    container_name: immich-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - /mnt/.ix-apps/app_mounts/immich/redis:/data
    networks:
      - immich

  immich-db:
    image: postgres:15
    container_name: immich-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=immich
    volumes:
      - /mnt/.ix-apps/app_mounts/immich/postgres:/var/lib/postgresql/data
    networks:
      - immich
