version: "3.8"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host            # fastest for throughput on SCALE 25.10
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - LOG_CONFS=true
    volumes:
      - /mnt/software/ix-applications/wireguard/config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
#    sysctls:
 #     - net.ipv4.conf.all.src_valid_mark=1   
    restart: unless-stopped
    cpuset: "4-9"                   # pin container to cores 4-9 (adjust if needed)
