version: "3.8"

networks:
  wgnet:
    driver: macvlan
    driver_opts:
      parent: br25
    ipam:
      config:
        - subnet: "192.168.0.0/23"
          gateway: "192.168.1.254"
          ip_range: "192.168.1.160/29"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      wgnet:
        ipv4_address: 192.168.1.125
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - LOG_CONFS=true
    volumes:
      - /mnt/software/ix-applications/wireguard:/config
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
