#version: '3.7'

services:
  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    container_name: whisparr
    restart: unless-stopped
    ports:
      - 6969:6969    
    environment:
      - PUID=1000        # Set the user id (PUID) of the container
      - PGID=1000        # Set the group id (PGID) of the container
      - DB_PATH=/config/whisparr.db # Database path
    volumes:
      - /mnt/.ix-apps/app_mounts/whisparr/config:/config # Persistent config data (adjust this path)
      - /mnt/HawkPool/Media/Center/OtherStuff:/media # Link to your TV shows library (adjust path)
    networks:
      - proxy  # Attach to the same Traefik network

    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # Define the rule for routing traffic to this container
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.${CF_DOMAIN}`)"  # Adjust for your domain
      - "traefik.http.routers.whisparr.entrypoints=websecure"  # Use the HTTPS entrypoint
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"  # Expose port 8181 of the container
      - "traefik.http.routers.whisparr.tls=true"  # Enable TLS (HTTPS)
      - "traefik.http.routers.whisparr.tls.certresolver=cloudflare"  # Use your Cloudflare certresolver

networks:
  proxy:
    external: true
