#version: "3.9"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DOMAIN: ${CF_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/.ix-apps/app_mounts/traefik/config:/etc/traefik
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.watch=true" 
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=partybringer@hotmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--serverstransport.insecureskipverify=true"
      - "--entrypoints.websecure.http.tls.certresolver=cloudflare"
      - "--entrypoints.websecure.http.tls.domains[0].main=hawknest.quest"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.hawknest.quest"
    labels:
      # --- Dashboard ---
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host("traefik.${CF_DOMAIN}"")"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.middlewares=lanonly@file,basicauth@file,secureHeaders@file"


# optional security: dashboard limited to LAN
    extra_hosts:
      - "host.docker.internal:host-gateway"
