#version: "3.9"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=partybringer@hotmail.com               # your Cloudflare email
      - CF_DNS_API_TOKEN=TzlsSxrCUdye3yC9HK5kweZBu1le_6UeFGGllGuA # DNS API token with edit zone access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/.ix-apps/app_mounts/traefik/config:/etc/traefik
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=partybringer@hotmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--serverstransport.insecureskipverify=true"
      - "--entrypoints.websecure.http.tls.certresolver=cloudflare"
      - "--entrypoints.websecure.http.tls.domains[0].main=hawknest.quest"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.hawknest.quest"
    labels:
      # --- Dashboard ---
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hawknest.quest`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.middlewares=lanonly@file,basicauth@file,secureHeaders@file"

      # --- Jellyfin ---
      - "traefik.http.routers.jellyfin.rule=Host(`jelly.hawknest.quest`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
      - "traefik.http.routers.jellyfin.middlewares=secureHeaders@file"
      - "traefik.http.services.jellyfin.loadbalancer.server.url=http://192.168.1.125:8096"

      # --- Jellyseerr ---
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.hawknest.quest`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=cloudflare"
      - "traefik.http.routers.jellyseerr.middlewares=secureHeaders@file"
      - "traefik.http.services.jellyseerr.loadbalancer.server.url=http://192.168.1.125:30042"

      # --- Invidious ---
      - "traefik.http.routers.invidious.rule=Host(`invidious.hawknest.quest`)"
      - "traefik.http.routers.invidious.entrypoints=websecure"
      - "traefik.http.routers.invidious.tls.certresolver=cloudflare"
      - "traefik.http.routers.invidious.middlewares=secureHeaders@file"
      - "traefik.http.services.invidious.loadbalancer.server.url=http://192.168.1.125:31008"

      # --- Jellystat ---
      - "traefik.http.routers.jellystat.rule=Host(`jellystat.hawknest.quest`)"
      - "traefik.http.routers.jellystat.entrypoints=websecure"
      - "traefik.http.routers.jellystat.tls.certresolver=cloudflare"
      - "traefik.http.routers.jellystat.middlewares=secureHeaders@file"
      - "traefik.http.services.jellystat.loadbalancer.server.url=http://192.168.1.125:30176"

      # --- Sabnzbd (LAN only) ---
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.hawknest.quest`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.tls.certresolver=cloudflare"
      - "traefik.http.routers.sabnzbd.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.sabnzbd.loadbalancer.server.url=http://192.168.1.125:30055"

      # --- Sonarr (LAN only) ---
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.hawknest.quest`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.sonarr.loadbalancer.server.url=http://192.168.1.125:30027"

      # --- Sonarr-Anime (LAN only) ---
      - "traefik.http.routers.sonarr-anime.rule=Host(`sonarr-anime.hawknest.quest`)"
      - "traefik.http.routers.sonarr-anime.entrypoints=websecure"
      - "traefik.http.routers.sonarr-anime.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr-anime.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.sonarr-anime.loadbalancer.server.url=http://192.168.1.125:30127"

      # --- Radarr (LAN only) ---
      - "traefik.http.routers.radarr.rule=Host(`radarr.hawknest.quest`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.radarr.loadbalancer.server.url=http://192.168.1.125:30025"

      # --- Radarr-Anime (LAN only) ---
      - "traefik.http.routers.radarr-anime.rule=Host(`radarr-anime.hawknest.quest`)"
      - "traefik.http.routers.radarr-anime.entrypoints=websecure"
      - "traefik.http.routers.radarr-anime.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr-anime.middlewares=lanonly@file,secureHeaders@file"
      - "traefik.http.services.radarr-anime.loadbalancer.server.url=http://192.168.1.125:30125"





# optional security: dashboard limited to LAN
    extra_hosts:
      - "host.docker.internal:host-gateway"
