[[server]]
name = "Local"
tags = ["Backup/Sync"]
[server.config]
enabled = true

##

[[server]]
name = "RaspberryPi"
tags = ["Backup/Sync"]
[server.config]
address = "https://192.168.1.199:8120"
enabled = true

##

[[stack]]
name = "huntarr"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/huntarr"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "notifiarr"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/notifiarr"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "omada"
tags = ["Backup/Sync"]
[stack.config]
server = "RaspberryPi"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/raspberrypi/omada"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "qbittorrentvpn"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/qbittorrentvpn"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "traefik"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/traefik"
environment = """
# ======================================
# Traefik / Cloudflare Environment
# ======================================

# Cloudflare credentials (preferred modern format)
CF_DNS_API_TOKEN=AJjcwH_qpu5F-2bTePINCMVMtgSUF8zVDRNCLxzq # CLOUDFLARE_API_KEY=your_global_api_key_here

# Optional legacy format (ignored if above is set)
CF_API_EMAIL=partybringer@hotmail.com 

# Domain (used in labels)
CF_DOMAIN=hawknest.quest



TZ=America/Chicago
"""