[[server]]
name = "Local"
tags = ["Backup/Sync"]
[server.config]
enabled = true

##

[[server]]
name = "RaspberryPi"
tags = ["Backup/Sync"]
[server.config]
address = "https://192.168.1.199:8120"
enabled = true

##

[[stack]]
name = "huntarr"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/huntarr"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "notifiarr"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/notifiarr"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "omada"
tags = ["Backup/Sync"]
[stack.config]
server = "RaspberryPi"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/raspberrypi/omada"
environment = """
TZ=America/Chicago
"""

##

[[stack]]
name = "qbittorrentvpn"
tags = ["Backup/Sync"]
[stack.config]
server = "Local"
poll_for_updates = true
linked_repo = "Hawknest"
run_directory = "stacks/hawknas/qbittorrentvpn"
environment = """
TZ=America/Chicago
"""